wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1669694368.966864
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      3:
      - 13
      - 23
      4: 3.7.15
      5: 0.13.5
      8:
      - 5
